name = "AIS"
uuid = "fb6ad45f-a8d2-4b73-9a55-6eb8386f3242"
authors = ["March <example.com> and contributors"]
version = "1.0.0-DEV"

[deps]
LibPQ = "194296ae-ab2e-5f79-8cd4-7183a0a5a0d1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
